function [] = AAT()

S.fh = figure('units','pixels',...
              'position',[600 300 200 300],...
              'menubar','none',...
              'name',' AT',...
              'numbertitle','off',...
              'resize','off');
          
S.text(1) = uicontrol('style','text',...
                 'unit','pix',...
                 'position',[0 255 200 30],...
                  'string','--------------- Processing ---------------');

S.pb(1) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[35 230 130 30],...
                 'string','Align sequences',...
                 'callback',{@align,S},...
                 'enable','on');   
             
S.pb(2) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[35 190 130 30],...
                 'string','Segmentation',...
                 'callback',{@segment,S},...
                 'enable','on');        
             
S.text(2) = uicontrol('style','text',...
                 'unit','pix',...
                 'position',[0 135 200 30],...
                  'string','---------------- Analysis ----------------');
             
S.pb(3) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[35 110 130 30],...
                 'string','Density',...
                 'callback',{@dens,S},...
                 'enable','on');                
              
S.pb(4) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[35 70 130 30],...
                 'string','Colocalization',...
                 'callback',{@coloc,S},...
                 'enable','on');
             
S.pb(5) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[35 30 130 30],...
                 'string','Plaque distance',...
                 'callback',{@plaque,S},...
                 'enable','on');

      
                        
     
S.NAME = {'No sequence selected'};

             
  

    function [] = align(varargin)
    % Callback for pushbutton.
             alignment
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = segment(varargin)
    % Callback for pushbutton.
             segment_GUI
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = dens(varargin)
    % Callback for pushbutton.
             density
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = coloc(varargin)
    % Callback for pushbutton.
             colocalization
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = plaque(varargin)
    % Callback for pushbutton.
             plaque_distance
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function preCloseMain(varargin)
      try 
%        fprintf('Closing non-main figures!\n');
        handles=findall(0,'type','figure'); % find all handles opened
        close(handles);
        close all;
      end 
%      fprintf('Closing main figure!\n');     
      delete(S.fh(1));
    end

end