function [] = segment_fixedGUI()

S.fh = figure('units','pixels',...
              'position',[800 300 150 300],...
              'menubar','none',...
              'name',' Segment',...
              'numbertitle','off',...
              'resize','off');

S.bg(2) = uibuttongroup('units','pix',...
                     'pos',[20 130 110 95]);   
                 
S.tx(5) = uicontrol(S.bg(2),...
                 'style','text',...
                 'unit','pix',...
                 'position',[5 65 90 25],...
                 'string','Filt object size');

S.tx(3) = uicontrol(S.bg(2),...
                'units','pixels',...
                 'style','text',...
                 'unit','pix',...
                 'position',[10 35 40 25],...
                 'string','From...');    
S.tx(4) = uicontrol(S.bg(2),...
                'units','pixels',...
                 'style','text',...
                 'unit','pix',...
                 'position',[10 5 40 25],...
                 'string','To...'); 
S.ed(4) = uicontrol(S.bg(2),...
                    'style','edit',...
                 'unit','pix',...
                 'position',[50 40 40 25],...
                 'string','3');    
S.ed(5) = uicontrol(S.bg(2),...
                    'style','edit',...
                 'unit','pix',...
                 'position',[50 10 40 25],...
                 'string','inf'); 
       
S.tx(1) = uicontrol('units','pixels',...
                 'style','text',...
                 'unit','pix',...
                 'position',[20 240 50 40],...
                 'string','Threshold value');    
S.ed(1) = uicontrol('style','edit',...
                 'unit','pix',...
                 'position',[80 253 50 25],...
                 'string','15');    

         
S.pb(1) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 20 110 30],...
                 'string','Analyze',...
                 'callback',{@analyze,S},...
                 'enable','off');
S.pb(2) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 60 110 30],...
                 'string','Previsualize',...
                 'callback',{@previsualiz,S},...
                 'enable','off');
S.fm = uimenu(S.fh,...
                 'label','Select path',...
                 'callback',{@fm_call,S},...
                 'enable','on');         
   
S.NAME = {'No sequence selected'};

             
    function [] = analyze(varargin)
    % Callback for pushbutton.
      
       Threshold_value = get(S.ed(1),'string'); 
        path = get(S.ed(3),'string');
        min_size = get(S.ed(4),'string');
        max_size = get(S.ed(5),'string');
        
        min_size = str2double(min_size);
        if strcmp(max_size,'inf')
            max_size = 999999;
        else
            max_size = str2double(max_size);
        end
        
        Thresholdvalue = str2num(Threshold_value);
        
 
        segment_fixed(path,Thresholdvalue,min_size,max_size)
        close (S.fh)


    end
  % Now reset the button features.
    



    function [] = previsualiz(varargin)
    % Callback for pushbutton.   % Get the structure.
     %   try
            Threshold_value = get(S.ed(1),'string'); 
            path = get(S.ed(3),'string');
            
            L = get(S.pp,'Value');
            name = S.NAME{L};

            min_size = get(S.ed(4),'string');
            max_size = get(S.ed(5),'string');

            min_size = str2double(min_size);
            if strcmp(max_size,'inf')
                max_size = 999999;
            else
                max_size = str2double(max_size);
            end
            Thresholdvalue = str2double(Threshold_value);
            
            fprintf('widnow size: %d \n',Thresholdvalue)
            fprintf('min object size: %d \n',min_size)
            fprintf('max object size: %d \n',max_size)
            fprintf('srcPath: %s \n',path)
            fprintf('seqName: %s \n',name)


            col = get(S.pb(2),'backg');  % Get the background color of the figure.
            pause(.01)
            set(S.pb(2),'str','RUNNING...','backg',[1 .6 .6]) % Change color of button. 

           segment_fixed_previsualize(path,name,Thresholdvalue,min_size,max_size)
  
            pause(.01)
            set(S.pb(2),'str','Previsualize','backg',col)  

    end

    function [] = fm_call(varargin)     
         try
            S.fh(2) = figure('units','pixels',...
                 'position',[470 250 300 100],...
                 'name','Select sequence to previsualize',...
                 'menubar','none',...
                 'numbertitle','off');
            S.ed(3) = uicontrol('units','pixels',...
                  'style','edit',...
                  'unit','pix',...
                  'position',[20 55 260 30],...
                   'string','No path selected');
               
            set(S.fh(1),'CloseRequestFcn', @preCloseMain);
            srcPath = uigetdir('Select the sequence path'); %DIRECTORI  ON ESTAN LES IMATGES
            Files = strcat(srcPath,[filesep '*.tif']);  % the folder in which ur images exists
            srcFiles = dir(Files);
            
            for i=1:length(srcFiles)
                names{i} = srcFiles(i).name;
            end
            S.NAME = names;
            
            set(S.ed(3),'string',srcPath);
            S.pp = uicontrol(S.fh(2),...
                    'style','popupmenu',...
                    'unit','pixels',...
                    'position',[20 15 260 30],...
                    'string',S.NAME);
                set(S.pb,{'enable'},{'on'});
         catch
            disp('Unable to Load.  Check Name and Try Again.')
         end
    end

    function preCloseMain(varargin)
      try 
%        fprintf('Closing non-main figures!\n');
        close(S.fh(2));
        
        handles=findall(0,'type','figure'); % find all handles opened
        close(handles);
      end 
%      fprintf('Closing main figure!\n');     
      delete(S.fh(1));
    end
    end
    

